RackHD/on-core

lib/common/constants.js

Added supported obm setting in constants
https://hwjiraprd01.corp.emc.com/browse/MAG-222
related PRs:
https://github.com/RackHD/on-tasks/pull/55
https://github.com/RackHD/on-http/pull/28

Added supported obm setting in constants

---

.travis.yml
HWIMO-TEST
README.md
package.json

This should be good... except that the Node4 based build is being a little (*^*&#%*&@!%#@ and periodically failing with indeterminate errors...

Build status

---

lib/di.js
lib/extensions.js

This and Rolands PR https://github.com/RackHD/on-core/pull/29 will fix all of the jshint errors

fixing jshint score

---

lib/common/encryption.js
lib/services/statsd.js

@tldavies here are the code style fixes you asked for this morning.

Fix checkstyle warnings

---

lib/common/file-loader.js
spec/lib/common/file-loader-spec.js

Filter directories from file-loader list

---

lib/common/logger.js
spec/lib/common/logger-spec.js

Allow filtering of log messages based on severity level

---

lib/common/profile.js
lib/common/template.js
spec/lib/common/profile-spec.js
spec/lib/common/template-spec.js

Fixes https://github.com/RackHD/RackHD/issues/40
@heckj @kacole2

Fix bug with calling waterline create with a buffer

---

lib/common/template.js
spec/lib/common/template-spec.js

Fix update not specifying scope

---

lib/common/constants.js
spec/lib/common/logger-spec.js

final pull request to resolve https://github.com/RackHD/RackHD/issues/34
**NOTE**: Requires all other PR's for log normalization in projects
using on-core to be merged prior to merging this PR. As I'm setting this
up, only https://github.com/RackHD/on-tasks/pull/95 remains to be merged
prior to this PR

log level reduction

---

lib/services/error-publisher.js

@stuart-stanley 
on-http unit test failed without this PR on my side. It might also help on smoke test.

change log level from alert to critical in error publisher

---

lib/common/messenger.js

@RackHD/corecommitters @RackHD/rackhd_dev

Clarify AMQP tx/rx connection error messages

---

lib/common/template.js
spec/lib/common/template-spec.js

@RackHD/corecommitters @tannoa2 @uppalk1 @keedya

Add unlink method to TemplateService

---

lib/common/constants.js

Fix typo for logging.critical coloring constant

---

spec/lib/protocol/events-spec.js
spec/lib/protocol/scheduler-spec.js
spec/lib/protocol/task-graph-runner-spec.js
spec/lib/protocol/task-spec.js
spec/lib/protocol/waterline-spec.js

- Remaining protocols tests
- Remove rabbitmq-server dependency.
@RackHD/corecommitters @keedya @zyoung51 @uppalk1 @tannoa2

Refactor on-core unit-tests

---

spec/lib/protocol/dhcp-spec.js

- Remove rabbitmq-server dependency.
@RackHD/corecommitters @zyoung51 @keedya @uppalk1 @tannoa2

Refactor dhcp-spec unit-test

---

README.md
lib/common/constants.js
lib/services/configuration.js
spec/lib/services/configuration-spec.js

@heckj @benbp 
Please do not merge, blocked...

removed refs to onRack

---

.dockerignore
Dockerfile
lib/services/configuration.js

* Switched to an alpine linux base image with node v4 installed. 
* Install git on base image.
* Added a error message when configuration file is missing.

Switch Dockerfile to Alpine Linux

---

lib/models/environment.js
lib/services/environment.js
spec/lib/services/environment-spec.js

- Allow the user to establish arbitrarily named environment
collections and merge/retrieve items from those arbitrary
environments in a priority order.

Add environment collection with hierarchy support

---

spec/lib/common/model-spec.js
spec/lib/common/subscription-spec.js
spec/lib/models/catalog-spec.js
spec/lib/models/file-spec.js
spec/lib/models/graph-definition-spec.js
spec/lib/models/graph-object-spec.js
spec/lib/models/log-spec.js
spec/lib/models/lookup-spec.js
spec/lib/models/node-spec.js
spec/lib/models/profile-spec.js
spec/lib/models/sku-spec.js
spec/lib/models/task-definition-spec.js
spec/lib/models/template-spec.js
spec/lib/models/work-item-spec.js

@jlongever @uppalk1 @keedya @RackHD/corecommitters @zyoung51

Model spec refactor

---

lib/common/constants.js
lib/common/db-renderable-content.js
lib/common/profile.js
lib/common/template.js
lib/models/profile.js
spec/lib/common/db-renderable-content-spec.js
spec/lib/common/profile-spec.js

- Refactor Template/Profiles to combine scoping support logic for
both into DbRenderableContent.

Add Profile scoping support for skupacks

---

lib/common/model.js
lib/extensions.js
lib/models/lookup.js
spec/lib/common/model-spec.js
spec/lib/models/lookup-spec.js

Resolves https://github.com/RackHD/RackHD/issues/129
The first commit just contains some incremental improvements including creating the right index structure. The second commit (3136f93) contains the actual fix to https://github.com/RackHD/RackHD/issues/129
Requires: https://github.com/RackHD/RackHD/pull/133
@RackHD/corecommitters @zyoung51 @tldavies

Fix lookup indexes handling

---

lib/common/errors.js
lib/models/local-user.js
lib/models/roles.js
package.json
spec/lib/models/localusers-spec.js
spec/lib/models/roles-spec.js

- Add local user model and use bcrypt to serialize passwords
- Add roles model
- Add 401 and 403 errors to the common errors

As part of the swagger AuthN/AuthZ changes:

---

lib/common/file-loader.js
spec/lib/common/file-loader-spec.js

@RackHD/corecommitters @uppalk1 @keedya @tannoa2

Add recursive directory traversal to file loader

---

lib/models/lookup.js
spec/lib/models/lookup-spec.js

Fixes https://github.com/RackHD/RackHD/issues/139

Fix potential null diplicate key error on lookups.ipAddress

---

lib/models/node.js
spec/lib/models/node-spec.js

resolve RackHD/RackHD#104
related PR https://github.com/RackHD/on-http/pull/186
@RackHD/rackhd_dev @RackHD/corecommitters @ytjohn

Add bootSettings in node model

---

lib/models/graph-object.js
lib/workflow/stores/mongo.js
spec/lib/workflow/stores/mongo-spec.js

* Modifications to workflow store by @srinia6 and @abildw
* Add active() method to graph-object model.

on-core changes required for 2.0 workflows routes.

---

lib/common/constants.js
lib/models/graph-object.js

* Add new ActiveStates constant.
* Change graph object model active method to use this constant.

Add Constants.Task.ActiveStates

---

lib/common/constants.js
lib/models/view.js

This change adds a constant and waterline model needed for https://github.com/RackHD/on-http/pull/206

Add views constant and waterline model

---

lib/common/constants.js

@RackHD/corecommitters @zyoung51 @geoff-reid @tannoa2 @keedya @uppalk1

Fix redfish obm service constants

---

lib/common/db-renderable-content.js
lib/common/errors.js

* Add ViewRenderError and InternalServerError with 500 status.
* Add check for valid template in db renderable render method.

Additional error handling for rendering views

---

lib/common/validatable.js
lib/models/node.js

supports https://github.com/RackHD/on-tasks/pull/150 and https://github.com/RackHD/on-tasks/pull/163 by adding optional sshSettings to node schema
@benbp

Ssh settings

---

lib/common/file-loader.js

@RackHD/corecommitters @uppalk1 @tannoa2 @keedya

Fix getAll to readFile with 'utf-8' specified

---

lib/common/system-uuid.js
spec/lib/common/system-uuid-spec.js

@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @zyoung51 @geoff-reid 
This PR is required for upcoming Redfish ServiceRoot fix and SSDP/UPnP PR.

Add module to read local system unique identifier

---

lib/common/constants.js

For ODR-593 and https://www.pivotaltracker.com/n/projects/1492888/stories/115448753

Adds running to active states constant

---

lib/common/constants.js

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya

Add Redfish EventTypes Constant

---

lib/common/constants.js

This is picked from https://github.com/RackHD/on-core/commit/3079b8f905c2450ecf3d16859dd1ef1252b98627 to make https://github.com/RackHD/on-tasks/pull/203 works

[1.2] Add Redfish EventTypes Constant

---

lib/models/task-dependency.js

fix for https://github.com/RackHD/RackHD/issues/228

removed misplaced unique flag

---

lib/workflow/stores/mongo.js
spec/lib/workflow/stores/mongo-spec.js

This fixes a bug with https://github.com/RackHD/on-http/pull/246 that causes workflows to never finish.

Update workflow mongo store queries for active states

---

lib/models/node.js
spec/lib/models/node-spec.js

and complete the TODO of changing to findAndModifyMongo command

Generate event when tags are added/removed

---

lib/common/constants.js

@RackHD/corecommitters @uppalk1 @zyoung51 @keedya @tannoa2

Add SSDP AMQP exchange constant definition

---

lib/common/constants.js
lib/common/model.js
lib/protocol/events.js
lib/protocol/waterline.js
lib/workflow/stores/mongo.js
lib/workflow/task-graph.js
spec/lib/workflow/stores/mongo-spec.js
spec/lib/workflow/task-graph-spec.js

* Adds task labels to task instance data. (required by the UI for operation center)
* Re-implements created waterline event when graphs are created AND updated. (required by the UI for realtime graphs)

Fix graph created event, and add label to task instances.

---

package.json

resolves https://github.com/RackHD/RackHD/issues/262
@johren @rolandpoulter @brianparry @hohene @RackHD/corecommitters

rolling back amqp to known good version

---

lib/common/encryption.js
spec/lib/common/encryption-spec.js

Remove support for md5 password hashing

---

lib/services/lookup.js

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

Always return promise when validating arp cache

---

lib/models/lookup.js
spec/lib/models/lookup-spec.js

Fix issue:
issue:https://github.com/RackHD/RackHD/issues/291
Related issues:
- Validate ssh task failed to lookup node  IP address

Save nodeId as a mongo object ID in Mongo 

---

lib/workflow/stores/mongo.js
spec/lib/workflow/stores/mongo-spec.js

remade the branch and PR .
@benbp @rolandpoulter 

added timestamp on task start and completion

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

Fix Jenkins failure, a mistake that missing return promise when no action for node's sku field. 
TypeError: Cannot read property 'catch' of undefined at /home/vagrant/src/on-tasks/lib/jobs/generate-sku.js:129
@RackHD/corecommitters @jlongever

Fix not returned promise

---

lib/common/model.js
lib/models/work-item.js
lib/workflow/stores/mongo.js
spec/lib/models/work-item-spec.js

Move database specific calls from the work-item model into the workflow

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

This is the PR to support https://github.com/RackHD/on-http/pull/377

Add southbound API to pass notification to RackHD (refer to ODR682)

---

index.js
lib/common/json-schema-validator.js

- Remove `Errors` injection which is not used
- Move `url` to index
@RackHD/corecommitters @iceiilin @cgx027 @pengz1

Clear dependency injection of json schema validator

---

lib/common/constants.js
lib/common/messenger.js
lib/models/node.js

* Adds ComputeContainer constant, and docker property to node model
* Adds custom timeout argument for messenger.subscribe

Changes needed for docker tasks in on-tasks.

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

This PR is depended by https://github.com/RackHD/on-http/pull/410

notification API design refactor

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

Reverts RackHD/on-core#191 as the Jenkins has some problem.

Revert "notification API design refactor"

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

This PR is depended by RackHD/on-http#410
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/311

Refactored notification api design

---

lib/common/db-renderable-content.js
spec/lib/common/db-renderable-content-spec.js

As discussed here: https://github.com/RackHD/RackHD/issues/286 with @yyscamper

Improve error message for renderable hash mismatch

---

lib/common/constants.js

part of https://github.com/RackHD/RackHD/wiki/proposal-passively-add-remove-a-rack-node 
adds the contains/containedBy relations
supports https://github.com/RackHD/on-http/pull/432
@RackHD/corecommitters  @pscharla

added rack node type and contains relationtype

---

lib/common/constants.js

Required for https://github.com/RackHD/on-http/pull/373
Added the following values to constants.js
```
HttpStatic: {
onhttpStaticHttp: 'static/http',
onhttpSkupack: 'skupack.d'
}
```

Constants for list static files

---

spec/lib/common/model-spec.js

resolves https://github.com/RackHD/RackHD/issues/385
The function `findSinceLastUpdate` lookups by `updatedAt`, but the unit-testing is using `createdAt`. Since the all time values include `updatedAt`, `createdAt` for all records are very close, so the time value in unit-testing doesn't always work as expected.
I have tested the unit-testing for more than 100 times, no error happens again.
@DavidjohnBlodgett @rolandpoulter @RackHD/corecommitters

Issue#385: Fix unit-test error due to model.findSinceLastUpdate

---

lib/models/roles.js
spec/lib/models/roles-spec.js

@RackHD/corecommitters @brianparry @zyoung51 @jlongever @srinia6 @dalebremner @BillyAbildgaard

Set role attribute in roles collection to be a unique index

---

lib/services/configuration.js

resolves https://github.com/RackHD/RackHD/issues/326
@heckj @RackHD/corecommitters

issue#326: change the log level of using default configuration value from info to warning

---

lib/workflow/stores/mongo.js
spec/lib/workflow/stores/mongo-spec.js

fix for https://github.com/RackHD/RackHD/issues/327 
goes with 
https://github.com/RackHD/on-tasks/pull/344
and 
https://github.com/RackHD/on-taskgraph/pull/172
@RackHD/corecommitters @pscharla

actually ignore failures if so marked

---

lib/models/graph-object.js
lib/models/task-dependency.js
lib/protocol/events.js
lib/workflow/messengers/messenger-AMQP.js
lib/workflow/stores/mongo.js
spec/lib/models/graph-object-spec.js
spec/lib/protocol/events-spec.js
spec/lib/workflow/messengers/messenger-amqp-spec.js
spec/lib/workflow/stores/mongo-spec.js

Changes includes:
1. Create progress property in taskdependencies, graphObject and its related methods
2. Create progress related events

On core changes for secure erase progress

---

lib/common/errors.js

It trapped me 2 hours just find this typo error. 
@RackHD/corecommitters  @iceiilin

fix inhenrence typo

---

lib/services/lookup.js
spec/lib/services/lookup-spec.js

Adds the ability to call an external script to fill in missing lookup entries.

External lookup helper support.

---

lib/common/messenger.js

Revert "DEBUG: revert Lyne's PR #233"

---

package.json

Prepare to Release
* change debian/package version and contacts.
@panpan0000 @PengTian0

[skip ci]modify debian info for release

---

lib/protocol/events.js
lib/workflow/messengers/messenger-AMQP.js
spec/lib/protocol/events-spec.js
spec/lib/workflow/messengers/messenger-AMQP-spec.js

* Previous code doesn't include clean logic on progress data processing flow
* New code are organized in small sub-functions
* No impact to existing progress event feature, but added graphId to
publishProgressEvent parameter list.

 Refator progress data processing code

---

lib/protocol/events.js
lib/services/heartbeat.js
spec/lib/protocol/events-spec.js
spec/lib/services/heartbeat-spec.js

1. adjust graph events to latest event format
2. fix formats and contents about node and heartbeat routing key
3. fix some indents

adjust graph events to latest format

---

lib/common/hook.js
lib/common/http-tool.js
lib/models/hooks.js
lib/protocol/events.js
lib/services/hook.js
package.json
spec/lib/common/hook-spec.js
spec/lib/common/http-tool-spec.js
spec/lib/protocol/events-spec.js
spec/lib/services/hook-spec.js

Jenkins depends on: https://github.com/RackHD/on-tasks/pull/383
* Hook features need database model and method to post data to user
provided url
* Thus hook model is created as well as hook publish method
* However hook publish method leverage http tool, http tool is moved from
on-task repo to lib/common

 Implement hook feature

---

lib/common/hook.js
spec/lib/services/hook-spec.js

* To let user subscribe interested data, filter is designed based on event message header for hook feature.
* User filter should be a Javascript style RE expression as a string in the design.
* All data will be filtered against user defined hook filters and only qualified data will be posted to webhook url.
* Each hook may have an array of filters, any filter condition can make an event eligible and sent to the hook.

Implement hook filter feature

---

lib/common/graph-progress.js
lib/protocol/events.js
lib/services/graph-progress.js
lib/workflow/messengers/messenger-AMQP.js
spec/lib/common/graph-progress-spec.js
spec/lib/protocol/events-spec.js
spec/lib/services/graph-progress-spec.js
spec/lib/workflow/messengers/messenger-AMQP-spec.js

Refactor workflow progress implementation with progress service design.
1) add graph progress service
2) move publishTaskFinished from TaskRunner into messenger-AMQP.js
3) fix value and maximum in progress from publishTaskFinished and publishTaskStarted
This PR is related with https://rackhd.atlassian.net/browse/RAC-4390
@RackHD/corecommitters @pengz1

Refine workflow progress

---

lib/common/model.js
spec/lib/common/model-spec.js

Add two base function 
```removeFromListById```
```removeFromListByIdentifier```
This two functions invoke ```findAndModify``` to atomically run native mongo array operation ```$pullAll```.

add remove item from list

---

.travis.yml
lib/models/environment.js
lib/models/file.js
lib/models/graph-object.js
lib/models/local-user.js
lib/models/lookup.js
lib/models/roles.js
lib/models/task-definition.js
spec/lib/common/model-spec.js

Fix unittest error like 'MongoError: Index with name: identifier_1 already exists with different options' in mongodb 2.6.x/3.x. It's a mongodb compatibility problem between 2.4.x and 2.6.x/3.x.  
new version prevent sails-mongo creating duplicated index operations. either 'primaryKey:true' or 'unique:true' would create index, so following creating index opertaion would be duplicated, so the solution is to remove duplicated create index operation.
I've checked that the indexes are the same before and after this PR, they're as below. there's no impacts.
```
> db.environment.getIndexes()
[
{
"v" : 1,
"key" : {
"_id" : 1
},
"name" : "_id_",
"ns" : "pxe.environment"
},
{
"v" : 1,
"unique" : true,
"key" : {
"identifier" : 1
},
"name" : "identifier_1",
"ns" : "pxe.environment"
}
]
> …
```

Resolve mongodb compatibility problem

---

lib/protocol/events.js
spec/lib/protocol/events-spec.js

1) update eventsProtocol.publishGraphFinished
2) update eventsProtocol.publishGraphStarted

add graphId and graphName for event of graphStarted and graphFinished

---

lib/common/timer.js

Fix nanosecond to second conversion in timer
@iceiilin @anhou

 Fix nanosecond to second conversion in timer

---

HWIMO-TEST

Fix: recover the environment after test.
@anhou @iceiilin @panpan0000

RAC-5843 : restore environment even if the test failed

---

Dockerfile

RAC-6092 bugfix: add source list to docker image

---

lib/common/constants.js

Signed-off-by: Anitha Srinivasan <anitha.srinivasan@emc.com>
@RackHD/committers @keedya

added cooling and power node types

---

Dockerfile

@geoff-reid @RackHD/corecommitters @RackHD/committers

add arg feature for on-core to set repo and tag in From

---

lib/common/db-renderable-content.js
spec/lib/common/db-renderable-content-spec.js

Signed-off-by: Kranti Uppala <kranti.uppala@dell.com>
jenkins: ignore

Edit the file streaming functionality for PUT /profiles and /templates apis 

---

lib/common/messenger.js

add processing of amqpSsl option in config file

---

.travis.yml
spec/lib/common/encryption-spec.js

Add nodejs 8 unit-test in travis-ci, failure is allowed

Enable node8 unittest in travis-ci
