- .travis.yml
node4 builds have been providing to be unstable in timing or race conditions of some form in the extended unit test. Due to that instability, I'm proposing we disable the node4 builds for now (sorry @rolandpoulter) and work to resolving them in a branch before re-enabling node4 in travis.
Commenting out the detail in .travis.yml so we don't loose it and can re-enable in a branch to work it out.
> disabling node4 .travis setting

- index.js
- lib/services/error-publisher.js
- lib/services/statsd.js
- package.json
Installing `gc-stats` takes a long time because it has to do a lot of native compilation. In order to make npm install for `on-core` and its dependents I propose removing it.
~~I think `statsd` was only being used to broadcast info from `gc-stats` and AMQP request times. So I removed that as well. I can add `statsd` back if this is needed for something.~~
@benbp @DavidjohnBlodgett @VulpesArtificem
> Remove gs-stats to speed up npm install

- .travis.yml
This was needed for `gc-stats`. Now that it is gone we can run on travis without sudo.
> Update travis config to remove sudo and g++

- lib/common/template.js
- lib/models/template.js
- spec/lib/common/template-spec.js
- Modify the model to add 'scope' and default it to 'global'
- Modify template retrieval to consider scope when returning documents
- Update/modify unittests
> GRIP-17: Add scoping to templates

- .gitignore
- lib/services/error-publisher.js
Shifting logging level for event loop blocks under 50ms (from 100ms) from Notice to Debug level logging, to work with update to enable log filtering, and https://github.com/RackHD/RackHD/pull/30 to quiet down the demonstration log output
> Quieter normal eventloop

- lib/models/lookup.js
- spec/lib/models/lookup-spec.js
Fix [Issue#47](https://github.com/RackHD/RackHD/issues/47).
Any detail, please go to that issue page.
@RackHD/corecommitters @iceiilin @WangWinson @cgx027 @pengz1 @sunnyqianzhang
> Issue#47: fix lookups doesn't return all records for empty query

- index.js
- lib/services/waterline.js
- package.json
While digging around looking at how we're reconnecting automatically on MongoDB, I saw we were downlevel and had some dead code enabled, so clipping things out and upgrading us to sails-mongo 11.5, which resolves https://github.com/RackHD/RackHD/issues/56.
Notes from @frey indicate that later versions of sails-mongo may not properly support the native drivers on unix, so taking a stab at this while I'm digging out the specifics of what is and isn't supported there.
According to https://docs.mongodb.org/ecosystem/drivers/node-js/, the underlying mongodb driver of 2.0.42 supports our versions of MongoDB and of Node.js:
- https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-language-node
- …
> Waterline updates

- lib/services/lookup.js
- package.json
- spec/lib/serializables/ip-address-spec.js
- spec/lib/services/lookup-spec.js
https://groups.google.com/forum/#!topic/rackhd/CiRQhVdkE38
Attempting to improve logging performance by introducing caching to lookup-service. First cache miss results in a DB query, subsequent cache lookups for the same IP or MAC address will wait for the first query to respond unless the there is already a valid entry in the cache.
This should greatly reduce number DB queries by the LookupService.
> Adds node ID caching layer to lookup service.

- lib/services/lookup.js
- spec/lib/services/lookup-spec.js
Main issue here was that I need to add `.catch` to calls to `waterline.lookups.findOneByTerm()` without it, it was not properly resolving cache promises. Which caused on-http to hang after the first cache lookup.
I also added better `null` caching and a `maxAge` of 30 seconds to the cache.
On my end there are still a few tests failing in on-http but I'm not sure if they are related or not, wanted to talk to Ben before I spent too much time debugging the remaining test failures.
This fixes a majority of the test failures currently in on-http.
> Fix LookupService caching for failed promises.

- lib/common/connection.js
- lib/common/messenger.js
- spec/lib/common/connection-spec.js
Instead, try to reconnect a bunch of times, and only fail if we exceed the maximum attempts.
https://www.pivotaltracker.com/story/show/111023884
resolves https://github.com/RackHD/RackHD/issues/59
> Do not fail service startup if AMQP is not immediately available

- index.js
- lib/extensions.js
- lib/models/sku.js
- lib/models/work-item.js
- package.json
- spec/helper.js
- spec/lib/models/sku-spec.js
This should be merged before the `on-http`, `on-syslog`, `on-tasks`, and `on-taskgraph` upgrades are merged. Those PRs will be opened shortly after this.
According to lodash changelog the `.flatten()` was changed to be shallow, so `.flattenDeep()` is now used instead to prevent breakage. Also when wrapping an object with lodash and then calling `.forEach()` will not iterate until `.value()` is called. It was changed to be lazily evaluated.
> Upgrade lodash to version 3.10.1

- lib/common/constants.js
Add node relation mapping table.
I listed relation and its class ("link" and "component") here. It is used currently only for deleting node and updating its target nodes, but might extent to other actions (CRUD) in the future.
We can classify node relations into two classes: "component" and "link". If the relation is "component", its subordinate nodes will be deleted (like enclosure and compute); if the relation is "link", the target nodes will only be updated (like pdu and compute).
related PR:
https://github.com/RackHD/on-http/pull/80
> add node relation mapping table

- index.js
- lib/common/constants.js
- lib/serializables/log-event.js
- lib/services/argument-handler.js
- spec/lib/serializables/log-event-spec.js
- spec/lib/services/argument-handler-spec.js
Change includes:
- default turn off colorful output, user can turn on the colorful output by configuration: --color or --logColorEnable
- create argument handler service as the common place for argument handling. 
- print full log level name
- print caller uses the same color of corresponding log level
- change the color for 'debug' level to cyan
- improve LogEvent unittest coverage
this change is from the google group discussion [Remove the color code from RackHD log file]( https://groups.google.com/forum/#!topic/rackhd/7xtNfbg9jzM)
The code follows the implementation of the "colors" module: https://github.com/Marak/colors.js/blob/master/lib%2Fsystem%2Fsupports-colors.js#L34-L38
@RackHD/corecommitters @iceiilin @WangWinson @cgx027 @pengz1 @sunnyqianzhang
> improve log output (color/level/caller)

- lib/common/child-process.js
- spec/lib/common/child-process-spec.js
Change accepted exit code in child process from a number to an array, which is align with bootstrap.js running in the node.
> Use array for exit code in child process

- lib/common/validatable.js
- spec/lib/common/validatable-spec.js
- spec/lib/serializables/ip-address-spec.js
- spec/lib/serializables/mac-address-spec.js
This change is required to get the Swagger error handler to parse SchemaErrors properly (see https://github.com/RackHD/on-http/pull/119)
Swagger runs its error parser when next is called with a non-null error argument.  The error parser then uses util.isError to determine if the object is an Error.  Since util.isError only returns true if Object.prototype.toString.call(err) returns '[object Error]', util.isError returns false when it is passed an instance of jsonschema.SchemaError.  My solution is to wrap the SchemaError object in an Error object.
I'm not convinced this is the best way to solve this problem, so I'm open to suggestions.
> Force util.isError to return true for SchemaErrors

- spec/lib/services/encryption-spec.js
- spec/lib/services/lookup-spec.js
- spec/lib/services/messenger-spec.js
- spec/lib/services/waterline-spec.js
- Remove core service dependencies (mongo,rabbitmq) from services tests. 
@RackHD/corecommitters @keedya @zyoung51 @uppalk1 @tannoa2
> Refactor on-core service unit-tests

- lib/models/lookup.js
This handles a problem where we have a lookup record of mac->nodeId created by the linux cataloger job (analyzing `lshw` output), then later an ipAddress is associated with the record, and then later the DHCP lease expires and the IP is handed out elsewhere. The code in this case does not seem to succeed in re-creating the lookup document without the IP address, and it later gets created without any `node` attribute on reboot, thus causing lookup failures during OS installer workflows.
It seems that the waterline promise object probably doesn't execute the request until `.then()` is called, which is why adding a `return` statement makes this work, because before the `self.create` call was never executed.
> Attempt fix for lookup record race condition

- lib/models/node.js
- lib/models/tags.js
- spec/lib/models/node-spec.js
- spec/lib/models/tags-spec.js
- Modify node model to have a tags array and add $addToSet and $pull native
mongo commands to modify the array
- Create a tags model with SKU model based rules
> Node Tagging:

- lib/protocol/events.js
- lib/workflow/messengers/messenger-AMQP.js
- lib/workflow/stores/mongo.js
- lib/workflow/task-graph.js
- spec/lib/protocol/events-spec.js
- spec/lib/workflow/messengers/messenger-amqp-spec.js
- spec/lib/workflow/stores/mongo-spec.js
- spec/lib/workflow/task-graph-spec.js
Persist task error messages in the graph document. This makes it easier to debug failed workflows. Minor feature regression.
@RackHD/corecommitters @VulpesArtificem
> Persist task error messages

- .travis.yml
Travis will allow Node 5 to failures. Node .10 and 4 have to pass.
> Update travis to build node 5

- lib/services/configuration.js
- spec/lib/common/logger-spec.js
When running the unit-test in on-http, there will be plenty of Service.Configuration deprecated warning, it floods the console and hide those normal output. 
This warning is intended to ensure the `start` is called before query configuration, but the `start` does nothing right now. So it's safe to simply remove this warning.
Of course, there are alternative ways to achieve this:
(1) Make sure the cofiguration.start is called in any service, so I need to change every repo's index.js or add the configuration.start in on-core's index.js.
(2) Still enable this deprecated warning reporting, but constraint it is only report once for each service runtime.
My PR just choose the most simple fix, I have no preference on these 3 solutions and I'm happy to change it to another one if reviewer thinks …
> remove configuration service deprecated warnning

- spec/helper.js
This is part of fix for https://github.com/RackHD/RackHD/issues/138
if the workflowInjetables are not added into the unit-test dependencies, then it bring much difficulty to every unit-test file if it depends on those modules that stored in workflowInjectables.
@RackHD/corecommitters @iceiilin @WangWinson @cgx027 @pengz1 @sunnyqianzhang
> add workflowInjectables to unittest dependencies

- lib/common/constants.js
- lib/serializables/log-event.js
- spec/lib/serializables/log-event-spec.js
I see we forgot to add some sensitive words into the redaction list, for example:
- "plainPassword" & "encryptedPassword" & "rootPassword" & "rootEncryptedPassword" for OS bootstrap jobs.
- "serverPassword" for all Dell RACDAM tasks.
- "community" for snmp.
This will cause to leak those sensitive information as they will be recorded in log files.
If adding these words one by one, the redaction list will become so big, so I changed the redaction to support the regex.
@RackHD/corecommitters @iceiilin @cgx027 @sunnyqianzhang @pengz1
> change redaction to support regex and expand the redaction list

- index.js
- lib/services/error-publisher.js
- package.json
From a conversation with @benbp about changing the threshold for "Event Loop Blocked" appearing in the logs. Ultimately I thought we should remove this, because I believe it really does more harm than good. Mainly because `setInterval` is not very accurate, and even with an idle RackHD you'll still see "Event Loop Blocked" (50ms) debug logs.
I've seen people in RackHD ask about these logs, and that makes me feel they are somewhat confusing and noisy. Not really something that should be running in production.
We should use data from our automated tests to figure out where bottlenecks are and not rely on this kind of mechanism.
> Removes event loop blocked detection.

- package.json
- spec/lib/common/child-process-spec.js
@RackHD/corecommitters 
According the `assert-plus` the only breaking change from version 0.1.5 to 1.0.0 is that it will now accept Infinity as a Number.
I don't think RackHD will be affected by this breaking change. Updating the version fixes an issue where `assert.optionalArrayOfNumber` failed when given null. This was a bug in the older version of `assert-plus`
See https://github.com/RackHD/RackHD/issues/177
> Bump node-assert-plus version to fix assert.optionalArrayOfNumber

- lib/common/db-renderable-content.js
The `FileLoader` [getAll] (https://github.com/RackHD/on-core/blob/master/lib/common/file-loader.js#L59) method has already support load file recursively in sub folder, set `recursive` true to enable add templates and profiles in sub folder.
@RackHD/corecommitters @sunnyqianzhang @iceiilin @cgx027 @pengz1
> Set recursive to true when load templates

- lib/protocol/task.js
resolve https://github.com/RackHD/RackHD/issues/191 .  from https://github.com/RackHD/on-taskgraph/blob/master/lib/task-scheduler.js#L382 . we can see that the default 2nd and 3rd parameters of cancel()  is index and length, not errName and errMessage, and if index and length are treated as errName and errMessage, it will lead to  https://github.com/RackHD/on-core/blob/master/lib/protocol/task.js#L53  functions' failure, and break https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L185 's cancelTask() execution, and lead to amqp's subscription not be cleaned up
> Remove wrong parameters for taskprotocol's cancel

- lib/models/work-item.js
- spec/lib/models/work-item-spec.js
This patch includes changes to the work-item model that are needed to remove serializables from the 2.0 API pollers route. Changes convert the pollers resource "type" property to "name" and redact passwords from poller config.
> Changes to work-item model

- lib/models/task-dependency.js
- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
changed the mongo store setIndexes function to read a 'unique: true' flag and call the underlying method for  creating unique indexes in order to restore uniqueness constraints lost in the Big Taskgraph Refactor.
supports https://github.com/RackHD/on-taskgraph/pull/96
@RackHD/corecommitters @rolandpoulter
> added unique flag for indexes

- package.json
This is the same PR to https://github.com/RackHD/on-core/pull/139 but for the release/1.2.0-branch
> [1.2.0-branch] locking version of apache-crypt to be 1.0.9 to fix on-core

- index.js
This change allows RackHD modules to use the DI from on-core instead of requiring them to have their own DI in package.json:dependencies.
> Fix core/index to include its own default di

- lib/common/constants.js
- lib/models/lookup.js
- lib/services/lookup.js
- spec/lib/models/lookup-spec.js
- spec/lib/services/lookup-spec.js
In order to support running the RackHD on-taskgraph and on-http services on a host that does not have Layer-2 network access to the PXE network we need a host that does have access to the PXE network and can proxy requests to the southbound API endpoint over a management network.  
The proxy server, nginx in my POC, adds headers to the requests coming from the PXE client that contain headers that will be used during profile, template, and task rendering.
The headers are
X-Real-IP - the actual IP address of the PXE client
X-RackHD-api-proxy-ip - The IP address of the API proxy server
X-RackHD-api-proxy-port - The port of the API proxy server
The proxy server URL is added to the lookup record for the PXE client so that it can be used during task rendering since the original HTTP request is …
> Add support for southbound API proxy server

- lib/common/arp.js
- lib/services/lookup.js
- spec/lib/common/arp-spec.js
- spec/lib/services/lookup-spec.js
Moves the ARP handler into the lookups services deprecating ARP poller in on-taskgraph.  
Solves a couple known issues with existing ARP poller design:
1. Potential race condition when issuing a POST to /lookups on an IP change,  current ARP poller may see the ARP entry update and update the entry resulting in 500 response on the POST.
2. The existing poller runs as a job in on-taskgraph creating the prerequisite to run on-taskgraph on the same host that is taking the IP request from a client to ensure the hosts ARP table is current.  
@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya
> Move ARP handler into lookups service

- package.json
copy of #155 for the 1.2 release branch
> pinning AMQP to version without event emitter leak

- lib/common/model.js
- spec/lib/common/model-spec.js
Prevents an exception from being thrown when the record is falsy.
```
6:47:14 PM graph.1 |  [error] [2016-06-07T18:47:14.703Z] [on-taskgraph] [TaskGraph.CompletedTaskPoller] [Server] Error handling potential finished graphs
6:47:14 PM graph.1 |   -> /lib/completed-task-poller.js:257
6:47:14 PM graph.1 |  error:
6:47:14 PM graph.1 |  stack:
6:47:14 PM graph.1 |    """
6:47:14 PM graph.1 |      TypeError: Cannot read property 'instanceId' of null
6:47:14 PM graph.1 |          at ModelFactory.Waterline.Collection.extend.publishRecord (/home/vagrant/src/on-taskgraph/node_modules/on-core/lib/common/model.js:64:26)
6:47:14 PM graph.1 |          at Object.exports.publishGraphRecord (/home/vagrant/src/on-taskgraph/node_modules/on-core/lib/workflow/stores/mongo.js:26:39)
6:47:14 PM graph.1 | …
```
> Fix collection.publishRecord when called without a record

- lib/protocol/events.js
- spec/lib/protocol/events-spec.js
one part of spec https://github.com/RackHD/RackHD/wiki/proposal-AMQP-notifications-on-node-discovery-or-inaccessibility, node remove and inaccessible alert will be in a following PR
the alert publish method will also be used for node removed and inaccessible or other node's state in future
related PRs:
https://github.com/RackHD/on-tasks/pull/240
https://github.com/RackHD/on-taskgraph/pull/121
@RackHD/corecommitters @iceiilin @WangWinson
> Node discovered alert

- package.json
The new version does not throw a String when it cant find the file to tail.
> this updates always-tail to the newest version 0.2.0. 

- index.js
- lib/common/json-schema-validator.js
- package.json
- spec/lib/common/json-schema-validator-spec.js
This is a base class for json schema validation.
As  @yyscamper 's design.
- Ajv library should be leveraged to validate JSON schema
- In this initial version, expose `validate`, `addSchema`, `getSchema` function
- Detail implement of skip `context` validate will be in the subclass in on-tasks
> Create JsonSchemaValidator using Ajv lib

- HWIMO-TEST
Based on the build machine, the Task/TaskGraph AMQP messenger plugin can take more than the default allotment of 2000ms.  The timeout was upped significantly to 20000ms.
Ran this on our local build machine that was experiencing the failures to verify.
@RackHD/corecommitters @benbp @jlongever @heckj
> Update Task/TaskGraph AMQP messenger plugin to have big timeout.

- lib/common/json-schema-validator.js
- spec/lib/common/json-schema-validator-spec.js
While `getSchema` function return the original schema added to the validator instance,
`getSchemaResolved` is to return a schema with reference resolved.
example:
```JSON
{
"id": "/refschema/r1",
"definitions": {
"url": {
"type": "string",
"format": "uri"
}
},
"properties“: {
”repo": {
"$ref": "#/definitions/url"
}
}
};
``` 
after resolve
```JSON
{
"id": "/refschema/r1",
"definitions": {
"url": {
"type": "string",
"format": "uri"
}
},
"properties": {
"repo": {
"type": "string",
"format": "uri"
}
}
};
```
@RackHD/corecommitters @cgx027 @iceiilin
> add getSchemaResolved function

- lib/common/errors.js
- lib/models/node.js
- lib/models/obms.js
- lib/services/waterline.js
- spec/lib/models/node-spec.js
- spec/lib/models/obms-spec.js
* Create new obms model and tests.
* Remove obmSettings property from nodes resource.
* Add 1-N relation from nodes to OBMs
Supports:
https://github.com/RackHD/on-http/pull/312
https://github.com/RackHD/on-tasks/pull/243
https://github.com/RackHD/on-http/pull/334
> Replace node.obmSettings with obms collection.

- lib/common/json-schema-validator.js
- spec/lib/common/json-schema-validator-spec.js
add functions to json-schema-validator:
1 - `validatePatternSkipped`: validate the data against schema, but skip some validation if the error matches the skip-patterns. This is to support task schema upfront validation, which need to skip all context template.
2. `reset`: reset the validator to initial state.
@RackHD/corecommitters @WangWinson @iceiilin @cgx027 @pengz1
> json-schema-validator: add validatePatternSkipped & reset function

- lib/common/json-schema-validator.js
The issue was found when working on task annotation.
Since the baseId (`rackhd/schemas/v1/tasks/xxxxx`) scope changed, some $ref not been replaced correctly.
@RackHD/corecommitters @cgx027 @iceiilin
> Fix nested ref not resolved issue for incorrect baseId

- lib/common/constants.js
- lib/services/heartbeat.js
- spec/lib/services/heartbeat-spec.js
- Implements https://github.com/RackHD/RackHD/wiki/RackHD-Heartbeat-Event
- Periodically publish AMQP message with basic process and timestamp data for each running service.
- Configurable send interval, default to 10s. 
- Unit-tests
@RackHD/corecommitters @zyoung51 @tannoa2 @keedya @uppalk1
> Add heartbeat event service

- lib/models/work-item.js
- spec/lib/models/work-item-spec.js
This PR is to add alert capability in workitem .setFailed and .setSucceededwhen methods when pollers status changed and it is decided node alert should be issued.
A new argument is inserted in .setFailed and .setSucceded method and old tasks might be impacted and need update.
Code is Verified on D51, vPDU.
Related PR:
https://github.com/RackHD/on-tasks/pull/262
> Create alert for poller status changes

- lib/models/node.js
- lib/models/obms.js
- lib/models/work-item.js
- lib/protocol/events.js
- spec/lib/models/obms-spec.js
- spec/lib/models/work-item-spec.js
- spec/lib/protocol/events-spec.js
docs: https://github.com/RackHD/docs/pull/296  'discovered' and 'removed' related PRs have been merged in previous PRs
there are some limitations to achieve functionality in waterline lifecycle functions, so implement in related places, this is a common function could be leveraged in other places
@RackHD/corecommitters @zyoung51 @WangWinson
> Support node attribute change event

- lib/protocol/events.js
- spec/lib/protocol/events-spec.js
funciton publishEvent() has been used and the migration is finished, so remove deprecated publishNodeAlert() , also fix the missing ‘_' in previous commit by mistake.
@RackHD/corecommitters @WangWinson @yyscamper
> remove deprecated publishNodeAlert

- lib/common/json-schema-validator.js
- spec/lib/common/json-schema-validator-spec.js
- Support customize namespace in `options.nameSpace` when instantiation.
- Add APIs `addSchema`, `addSchemas`, `addSchemasByDir` to add schemas via namespace.
- Add API `getAllSchemaNames` to return all schema names.
- Update API `getSchema` with namespace resolved.
- Add unit test for new added function.
@RackHD/corecommitters @iceiilin @cgx027 @pengz1
> Update JsonSchemaValidator to handle schema with namespace

- lib/common/constants.js
- lib/models/graph-object.js
- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
supports https://github.com/RackHD/on-tasks/pull/261 added store methods for finding a child graph by its parent task id. @RackHD/corecommitters @pscharla
> added store method for finding child graph

- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
Adding basically a copy of the `checkGraphFinished` store method, but instead of querying for pending tasks, we query for pending AND failed tasks (i.e. != succeeded). This allows a higher level of the stack to prevent succeeding a graph when multiple terminal tasks finish at the same time, one with a failed state.
Fixes https://github.com/RackHD/RackHD/issues/295 along with https://github.com/RackHD/on-taskgraph/pull/137
@RackHD/corecommitters @stuart-stanley @VulpesArtificem
> Add check graph succeeded method

- lib/models/task-definition.js
- spec/lib/models/task-definition-spec.js
To support Task-Schema, a new key "schemaRef" is defined to store the reference of its task schema. Now it's set to be optional as not all existing tasks have associated schemas.
@RackHD/corecommitters @WangWinson @iceiilin
> add schemaRef in task-definition model

- lib/models/obms.js
- spec/lib/models/obms-spec.js
Adding the option to return decrypted values when calling the obm model's upsertByNode method. Supports https://github.com/RackHD/on-tasks/pull/313
@RackHD/corecommitters @hohene @johren
> Add revealSecrets option to models.obms.upsertByNode

- lib/common/model.js
- lib/common/sanitizer.js
- lib/workflow/stores/mongo.js
- spec/lib/common/sanitizer-spec.js
resolves RackHD/RackHD#241
new PR at the request of @brianparry 's to place logic into graph-object model.
due to a number of issues hit attempting to make my earlier code testable, I refactored to use encryption so passwords are not saved in our database in plain text to begin with and will be naturally concealed from the user on a query.
unit tests are complete for this feature.
> Redact passwords

- lib/models/obms.js
- spec/lib/models/obms-spec.js
This is to support the GET route for nodes/id/obm
@brianparry @RackHD/corecommitters @BillyAbildgaard @srinia6 @dalebremner @keedya
> added findAllByNode to Obms

- lib/common/db-renderable-content.js
- spec/lib/common/db-renderable-content-spec.js
Currently, when finding a template, all files with the same name will be returned, despite of the desired scope. If the there are 3 scopes (say ["a", "b", "global"]) in database, but user only want to find two of them (["a", "global"]), it is possible that the final file would be for scope "b" after sorting by priority.
Add scope filed when querying database.
@zyoung51
> add scope as a field when finding file in renderable db

- Dockerfile
Addresses an issue with `ipmitool` going missing from `apk`.
https://github.com/RackHD/RackHD/issues/394
> Changes Docker base image to debian wheezy

- lib/protocol/events.js
- spec/lib/protocol/events-spec.js
Related changes in `on-tasks`
https://github.com/RackHD/on-tasks/pull/350
Publish node event message with additional data, if provided.
> Updated node events to include additional data when published

- lib/workflow/stores/mongo.js
When only using default `rootPassword`, it fails ssh validation.
It is caused by the encripted password not being decripted in context when pulling the task data.
The payload used is
```
{
"options": {
"defaults": {
"version": "6.0",
"repo": "http://10.62.59.209/static/mirrors/esxi/6.0",
"rootPassword": "Password0",
"hostname": "rackhd",
"dnsServers": ["172.12.88.91"],
"ntpServers": ["0.vmware.pool.ntp.org", "1.vmware.pool.ntp.org"],
"installDisk": 0
}
}
}
```
@RackHD/corecommitters @panpan0000 @iceiilin
> Fix ssh validation failure when only using default rootPassword

- package.json
We are running the OnRack 1.2 branch on Ubuntu 14.04 which currently (in 14.04.5) has node 0.10.25.
on-core has a dependency on apache-crypt 1.0.9 which itself has an unpinned dependency on apache-md5.  In the 1.2.4 timeframe, the apache-md5 version installed was 1.0.6.  Sometime after
1.2.4 was released, a new version (1.1.1) of apache-md5 became available and is, therefore, now installed.   This version has code that requires node >=4.   
Therefore, with the latest 1.2 builds of on-http, on-taskgraph, on-tftp, on-syslog, and on-dhcp-proxy, these services fail to start up on Ubuntu 14.04 running node 0.10.25.
The solution we have implemented for 1.2.5 is to add a dependency of apache-md5 1.0.6 to on-core so that apache-crypt does not pull in version 1.1.1.   
Tested this with a debian …
> Pin apache-md5 to version 1.0.6

- lib/common/messenger.js
Modified RackHD on-core to allow an array of AMQP server IP addresses as an option during the AMQP connection call.
> RAC-170: RackHD support for multiple AMQP servers

- lib/common/model.js
- lib/common/sanitizer.js
- lib/workflow/stores/mongo.js
- spec/lib/common/sanitizer-spec.js
@RackHD/corecommitters 
Ok, so this guts the existing encryption I introduced... and I refactored the sanitizer object to serve up a single method that can be used to recursively redact secret fields... this PR will have a dependent PR within on-http to resolve the original issue:  https://github.com/RackHD/RackHD/issues/241
> Reverted Encryption at mongo store level, refactored Sanitizer Object.

- lib/common/model.js
- lib/models/catalog.js
- lib/models/environment.js
- lib/models/file.js
- lib/models/graph-definition.js
- lib/models/graph-object.js
- lib/models/local-user.js
- lib/models/lookup.js
- lib/models/node.js
- lib/models/obms.js
- lib/models/renderable.js
- lib/models/roles.js
- lib/models/sku.js
- lib/models/tags.js
- lib/models/task-definition.js
- lib/models/task-dependency.js
- lib/models/work-item.js
- lib/services/lookup.js
- lib/services/waterline.js
- lib/workflow/stores/mongo.js
- spec/lib/common/model-spec.js
- spec/lib/models/base-spec.js
- spec/lib/models/lookup-spec.js
- spec/lib/models/obms-spec.js
- spec/lib/models/roles-spec.js
- spec/lib/services/waterline-spec.js
- spec/lib/workflow/stores/mongo-spec.js
This PR originates from ODR-892 (https://hwjiraprd01.corp.emc.com/browse/ODR-892), @cgx027 found two problems about mongo index:
(1) some index settings in our code doesn't take effect.
(2) lack index for some frequently operation
I also found the waterline official doc said there is some outstanding bug about index, see https://github.com/balderdashy/waterline-docs/blob/master/models/data-types-attributes.md#index, meanwhile, the waterline doesn't support compound index.
I see some models (such as obm/lookups) will manually create mongo index, but most other models don't do this way.
This PR is to let the mongo index creation take effect for all models. The index can be defined in following two ways:
(1) In waterline attributes, if the `index` is set to `true`, code will auto extract the …
> fix mongo indexes creation for all models

- lib/common/messenger.js
"request" mechanism
---
in request function, both requester and responder use a queue to receive messages from their counterpart. In current code, the queue is exclusive, which means that it can only be acquired by one channel. Their names are in the same format "exchange:method.id:randomId"
problem
---
It is found that in scale environment (power on 350 nodes for discovery in an interval of 10s, host of rackhd 8G&4core), at a rate about 1/3, on-http (requester) tries to use a queue for taskExist message that is already owned by on-taskgraph (responder). the third-party shortId module for randomId generation is the most suspicious.
when this error occurs,
rabbitmq server repeats the following error
```
=INFO REPORT==== 11-Feb-2016::19:11:03 ===
accepting AMQP connection <0.17948.23> …
```
> modify queue name for messenger request function

- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
solves https://rackhd.atlassian.net/browse/RAC-1938
changed the mongo store checkGraphSucceeded method to succeed on graphs where the only task dependencies we find with waterline.taskdependencies.find are non-terminal.
@rolandpoulter @pscharla
> nonterminal, handled tasks no longer prevent graph from finishing

- lib/protocol/events.js
- lib/services/heartbeat.js
- spec/lib/protocol/events-spec.js
- spec/lib/services/heartbeat-spec.js
1. On lib.protocol, rename publishevent to publishExternalEvent
Check required field for external events in this function
2. Make changes to node event and heartbeat event, so that it conforms to the required fields for external event
@pengz1 @iceiilin @anhou @yyscamper
> Refactor publish external events to add several fields

- lib/common/json-schema-validator.js
- lib/models/task-definition.js
- spec/lib/models/task-definition-spec.js
Change including:
(1) Task-Definition: replace schemaRef with optionsSchema, optionsSchema can be either string or object, so set its type to `json`. 
(2) add removeSchema API for JSON schema validator;
@RackHD/corecommitters @iceiilin @pengz1 @cgx027 @lanchongyizu @amymullins
> support task-schema refactor

- lib/protocol/task.js
- spec/lib/protocol/task-spec.js
modify poller alert function to xxxLegacy, which will be used by on-tasks to be compatible with the old format. (The new event will use eventsProtocol.publishExternalEvent in on-core)
Jenkins: depend on https://github.com/RackHD/on-tasks/pull/391 https://github.com/RackHD/RackHD/pull/587
> modify poller alert function to be legacy

- lib/common/messenger.js
Multiple AMPQ servers are passed to amqp library as an array inside an object.
This changes the check of the uri parameter as an object instead of an array.
> Change check for multiple amqp URIs from an array to an object.

- lib/models/network-management.js
- lib/models/node.js
- spec/lib/models/node-spec.js
removing snmpSettings from lib/model/node.js
snmpSettings are moved from node to ibms
@RackHD/veyron
> addressing PR comments

- Dockerfile
https://rackhd.atlassian.net/browse/RAC-4215
The root base image of rackhd on-xxx docker images is ```nodesource/wheezy```
However, the source list of this base image can not satisfy our needs.
This sources list was used to be added in jenkins docker build steps.
As well as in https://github.com/RackHD/on-taskgraph/blob/master/Dockerfile for fixing some issue.
now we decide to add sources list in on-core(the root image of all on-xxx) for  unification.
Both https://github.com/RackHD/on-build-config/pull/80 and https://github.com/RackHD/on-taskgraph/pull/211 will remove the sources list add steps.
@panpan0000 
PR merge order:
This PR first, then after dockerhub autobuild success,
https://github.com/RackHD/on-taskgraph/pull/211 should be merged.
then the next day …
> [skip ci]add uniform sources list for docker images

- lib/protocol/task-graph-runner.js
It is found that in continuous functional test, "test_node_workflows_del_active" in CIT fails more than once per day. The reason is that RPC request of canceling taskgraph from on-http takes more than one second (usually 2s, from the vagrant log) to complete when on-taskgraph is busy evaluating other tasks during that period of time. In RackHD, the default timeout value for an RPC request is 1s. This PR changes the cancelTaskGraph request to 5s timeout
> add default timeout value for cancelTaskGraph

- spec/lib/services/lookup-spec.js
Recently, while I monitoring the Continuous Unit-Test result, I found there was a on-core unit-test error  pattern occurs one in a while, and I tried to stress the on-core unit-test in my local VM, I can reproduced this issue after running enough times (tens of rounds). This is one of the Jenkins job: http://rackhdci.lss.emc.com/job/Continuous-Test/job/Unit-Tests/job/on-core/29836/
I find the root cause is about a tricky async timing control for Promise in unit-test. With my fix in, I have tested the on-core unit-test for more than 100 times, no error happens again.
@anhou @brianparry @iceiilin @pengz1 @lanchongyizu @sunnyqianzhang
> fix random unit-test error due to Node ID Cache in lookup service

- lib/protocol/events.js
- lib/protocol/task.js
- spec/lib/protocol/events-spec.js
- spec/lib/protocol/task-spec.js
Remove Legacy events format support for the coming 2.0 release. the new event notification formats could be referenced at http://rackhd.readthedocs.io/en/latest/rackhd/event_notification.html
@RackHD/corecommitters @iceiilin @sunnyqianzhang @nortonluo
Jenkins: Depends on https://github.com/RackHD/on-tasks/pull/419
> Remove legacy events

- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
Partially fixes https://rackhd.atlassian.net/browse/RAC-637
supports https://github.com/RackHD/on-taskgraph/pull/226
@pscharla @RackHD/corecommitters 
Just return the undefined instead of crashing trying to query it.
> handle undefined graphs safely

- lib/workflow/stores/mongo.js
- spec/lib/workflow/stores/mongo-spec.js
This is a substitution of PR https://github.com/RackHD/on-core/pull/253
@pscharla
@VulpesArtificem
This is part of the change regarding adding waitOn.either feature to workflow engine.The Original task at following location:
https://github.com/RackHD/on-tasks/pull/405
Please Check the on-tasks PR regarding the request.
Please note that: Need to merge both PRs to enable this feature
jenkins: depends on https://github.com/RackHD/on-tasks/pull/405
> Clean up part for waitOn.anyOf

- lib/common/messenger.js
there's no time out value for 'message: Request Timed Out' message, add it
@RackHD/corecommitters @iceiilin @yyscamper @leoyjchang
> Refine timeout log

- spec/helper.js
Originally, unittest require modules in every round, it consumes a lot of memory, the problems is
when CI/CD environment is in heavy load, it's easy to cause 'Error timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.' due to lack of memory.. it's not necessary to consume unnecessary CPU and memory resources
Now move 'require' from every setupInjector() to global to avoid unnecessary requiring modules, it wouldn't affect RackHD functions, only limit to unittests, and all unit test cases have pass. benefits are
1. memory consumption reduce from ~500MB to ~300MB
2. unit test time decrease from ~17s to ~10s for 'on-core' unit test.  (4 cores/8GB mem in local machine), travisci unit test time decrease from ~27s to ~16s.
@RackHD/corecommitters @yyscamper …
> Reduce unittest memory consumption

- lib/di.js
Recently, we found below issue occurs in some systems.  The di cannot find the "consul" even I am sure the "consul" has been correctly installed `on-taskgraph/node_modules"
```
/RackHD/on-core/lib/di.js:492
throw new Error('dihelper incapable of finding specified file for require filename:' +
^
Error: dihelper incapable of finding specified file for require filename:consul, directories:(/RackHD/on-core, /RackHD/on-core/lib)
at _require (/RackHD/on-core/lib/di.js:492:13)
at Object.requireWrapper (/RackHD/on-core/lib/di.js:518:13)
at Object.<anonymous> (/RackHD/on-taskgraph/index.js:25:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain …
```
> Add process.cwd into di path

- lib/common/constants.js
Modifying name and location of smi config json used by the smi discovery and dell wsman inventory microservices.  
This serves two purposes:
1) removes wsman from the name 
2) pulls from a path that will be in both ansible and docker installations. 
This change should only affect the taskgraphs that invoke the SMI microservices.
Another PR to physically add the file to the monorail folder via the RackHD/RackHD repo should be committed around the same time.
> Modifying name and location of smi config json

- lib/common/model.js
- lib/models/work-item.js
- spec/lib/common/model-spec.js
1. Modfied ```findMongo, findAndModifyMongo, findOneMongo``` to return docs in normal format.
2. Add ```updateAndFindMongo``` to return modified doc(s) after update.
3. Add
```
addFieldIfNotExistById,
addFieldIfNotExistByIdentifier, 
addListItemsIfNotExistById,
addListItemsIfNotExistByIdentifier, 
```
For support some data consistency needs.
> add some DAL method support relation add data consistency

- lib/models/work-item.js
- lib/protocol/events.js
- spec/lib/models/work-item-spec.js
- spec/lib/protocol/events-spec.js
To implement feature for subscribing sel events, two changes are made:
1. Add AMQP methods for subscribeSelEvents
2. Add update poller configure methods to set SEL events filtering
> Add subscribe sel events methods

- lib/protocol/events.js
- lib/workflow/messengers/messenger-AMQP.js
- lib/workflow/stores/mongo.js
- spec/lib/protocol/events-spec.js
- spec/lib/workflow/messengers/messenger-AMQP-spec.js
**Background**
The current on-taskgraph log misses task and graph name, which makes developers hard to track workflow's actual behavior. It will be beneficial if adding their name into it. For more details, you can go to 
[https://rackhd.atlassian.net/browse/RAC-5456](url)
**Details**
To solve this problem, change the code of three repos: on-core, on-tasks, on-taskgraph. In on-core repo, add taskName and graphName into the  the function eventsProtocol.publishTaskFinished. Besides, add the responding changes to the unit test files.
Jenkins depends on: https://github.com/RackHD/on-tasks/pull/482, https://github.com/RackHD/on-taskgraph/pull/263
**TestDone**
test it successfully on ubuntu 14.04.exsi vm
**Reviewer**
@iceiilin @pengz1
> [RAC-5456] add taskName and graphName into on-taskgraph log

- lib/services/configuration.js
log message that reports default config settings is
being made level info instead of warning.
'Configuration value is undefined, using default'
> RAC-5804 - Change default config messages to be info

- lib/services/argument-handler.js
- lib/services/core.js
- lib/services/lookup.js
- lib/services/statsd.js
- spec/helper.js
- spec/lib/common/arp-spec.js
- spec/lib/common/child-process-spec.js
- spec/lib/common/connection-spec.js
- spec/lib/common/file-loader-spec.js
- spec/lib/common/system-uuid-spec.js
- spec/lib/protocol/events-spec.js
- spec/lib/services/environment-spec.js
- spec/lib/services/heartbeat-spec.js
- spec/lib/services/waterline-spec.js
**Backgroud**
This is for the story https://rackhd.atlassian.net/browse/RAC-5639.
During work of https://rackhd.atlassian.net/browse/RAC-5593, we found many unit test cases won't do the clean-up work if running into failure (aka exception handler) , so the plan is to add clean-up work in unit test cases.
**TEST**
It's tested in sandbox:
http://10.62.59.175:8080/job/on-core_jamie/
> clean up unit-test errors when it timeouts

- lib/common/constants.js
- lib/services/configuration.js
- spec/lib/services/configuration-spec.js
- Raises an exception when the configuration actually
fails during nconf load.  Previous message was based on
file's existence.
- Remove old references to OnRack configurations
> RAC-5819 - Clean up configuration-related logs

- lib/serializables/log-event.js
To fix this issue:
https://rackhd.atlassian.net/browse/RAC-5515
What the code change did:
1. Make the severity level the same length in logs. e.g. [  info  ], [critical], they have the same length
2. Remove the fields like [on-taskgraph][ TaskGraph.TaskScheduler], as they don't provide very useful information but makes the logs complicated.
Before code change, the log is like this:
0|taskgrap | [debug] [2017-08-09T08:53:30.463Z][on-taskgraph][ TaskGraph.TaskScheduler][ Server] Running job.
After the code change, the log is like:
0|taskgrap | [ debug  ] [2017-08-09T08:53:30.463Z] [ Server]Running job.
@anhou @pengz1 @iceiilin
> Make aggregated log column align and remove redundant field in logs

- HWIMO-TEST
The unit test depends on mongodb and rabbitmq.
The PR enhances the script HWIMO-TEST to run unit test with checking and setup dependencies.
@anhou @iceiilin @lanchongyizu @panpan0000
> RAC5843: enhance HWIMO-TEST to handle the dependencies

- lib/common/graph-progress.js
- spec/lib/common/graph-progress-spec.js
- spec/lib/services/graph-progress-spec.js
This is used to gather more information on task and taskgraph status when the task failed. Add the state field for both task and taskgraph so that the information is more clear. @iceiilin @pengz1
> Add taskgraph status and task status when the taskgraph failed

- Dockerfile
in on-taskgraph
Signed-off-by: Joe Gorse <joseph.gorseiii@emc.com>
depends on: https://github.com/RackHD/on-taskgraph/pull/281
> Remove sources list, manually download snmp

- HWIMO-TEST
Background
Mongo daemon command changed form 'mongodb' to 'mongod' after MongDB
2.6, this change is to accommodate both commands
Details:
Change mongo service command in HWIMO-TEST
>  Accommodate mongodb and mongod in HWIMO

- lib/common/http-tool.js
- spec/lib/common/http-tool-spec.js
Signed-off-by: Bala Balakumaran <bala.balakumaran@dell.com>
When a `Task.Base.Rest` is is used in a graph, it adds the outputs in the context which can then be refereed by subsequent tasks as `context.restData.body` however this is always a string. 
This PR allows the **body** to be converted to JSON if it is a valid JSON.
That way one can refer to ex: `context.restData.body.token`
> Converting http response to json if valid json

- lib/models/local-user.js
- package.json
- spec/lib/common/encryption-spec.js
**Background**
----
Currently, unit test will fail in Nodejs 6 and Nodejs 8.
[https://rackhd.atlassian.net/browse/RAC-6232](https://rackhd.atlassian.net/browse/RAC-6232)
**AC**:
- Paired with @mcgG  
- Fix nodejs6 and nodejs8 unit test failures in local machine
- Don’t break nodejs 4 unit test
- Pilot run in travisci environment(don’t commit the fix, because further FIT test should pass before submitting
**Detail**
----
*case 1*
HttpTool Should handle basic auth:
- Cause:
Nock: No match for request GET http://mysite.emc.com/basicAuth
- Fix:
Upgrade nock from 3.5.0 to 9.0.22
*case 2*
Models.LocalUsers Password functions should serialize a password
- Error:
Uncaught TypeError: The "digest" argument is required and must not be undefined
- Cause:
built-in module crypto changes api "pbkdf2()" …
> Fix node 6/8 unit test

- Dockerfile
- index.js
- lib/common/encryption.js
- package.json
The module apache-crypt@1.0.9 return different value in Node 4 and 6.
That leads to failure of unit test in node 6.
Fix:
Replace the module with crypt3@1.0.0
Test done:
Unit Test:
node 4: http://rackhdci.lss.emc.com/job/Archiving/job/tian/job/UnitTest_node4/109/
node 6: http://rackhdci.lss.emc.com/job/Archiving/job/tian/job/UnitTest_node6/134/
node 8 :http://rackhdci.lss.emc.com/job/Archiving/job/tian/job/UnitTest_node8/114/
Function Test:
Install ubuntu in quanta_d51 and succeed to login with user configured in payload.
Install centos 6.5 in quanta_d51 and succeed to login with user configured in payload.
@anhou @mcgg @iceiilin
> RAC-6432: failed to login os after upgrading module apache-crypt

- spec/lib/common/child-process-spec.js
- spec/lib/common/connection-spec.js
- spec/lib/common/json-schema-validator-spec.js
- spec/lib/common/subscription-spec.js
- spec/lib/services/hook-spec.js
RAC:  [https://rackhd.atlassian.net/browse/RAC-5743](https://rackhd.atlassian.net/browse/RAC-5743)
----
Paired with @PengTian0 
Using both `return promise` and `done()` in async unit test case will cause following error:
`Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`
According to Mocha's [official site](http://mochajs.org/):
`In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception`
**Solution**
----
Only call done() instead of return a promise in all async unit test cases.
@PengTian0 @pengz1 @anhou @iceiilin @bbcyyb
> Unit test fix for mocha update

- lib/common/connection.js
- lib/services/statsd.js
- package.json
- spec/lib/common/connection-spec.js
- spec/lib/protocol/dhcp-spec.js
- spec/lib/protocol/scheduler-spec.js
- spec/lib/protocol/task-graph-runner-spec.js
- spec/lib/protocol/task-spec.js
- spec/lib/protocol/waterline-spec.js
Paired with @mcgG 
Unit test doesn't exit after upgrading mocha to 4.0.1 because the new version of mocha won't exit if there are running process.
There are 3 kinds of cases that make mocha hangs
1. amqp: try to reconnect after disconnect(https://github.com/postwait/node-amqp/issues/462).
Fix: set the option "reconnect" to false in stop() to avoid the issue.
2. statsd: the socket is not closed after call statsd.stop()
Fix: call close() in stop() to close socket.
3. stub object messenger without restore. That leads to the messenger.stop() failed to stop amqp connection.
Fix: replace stub object with stub method of object in beforeEach. The stubbed methods will be restored in afterEach().
@mcgG @anhou @pengz1
> RAC-5743: unit test doesn't exit after upgrading mocha to 4.0.1

- lib/common/constants.js
- lib/common/errors.js
- spec/lib/common/errors-spec.js
Adding Redfish manager node type and adding a Defined Error for 501 Not Implemented
adding spec tests
************
Part of Changes in on-core, on-http, on-tasks, on-taskgraph
The combination of these changes is to fully implement redfish device discovery. This includes the fillowing items:
1) The implementation of unique device identifiers in place of the RackHD GUID identifers.
a) These ids provide the user the ability to know which node they are looking at. This is usefull for
aggregation.
b) All RackHD Redfish calls can use either the new id or the original RackHD GUID. The RackHD api still can
only use the GUID.
c) Currently this id is made with a combination of the serial number and sku from the redfish discovery.
2) Creation of redfish and redfishManager node types.
a) redfish nodes …
> WIP Adding redfish node for chassis/system combo

- lib/serializables/log-event.js
- spec/lib/serializables/log-event-spec.js
**Issue:**
Cannot assign to read only property '0' of string 'Task.Add.Hotspare'
https://rackhd.atlassian.net/browse/RAC-6774
**Root Cause:**
After upgrading node from v4 to v8, the property '0' of string turned
out read-only.
**Done:**
* Refine the code to avoid assigning to read only property of string. Only when the target is an array or object, we will recursively call the `_redact` function.
* Add unit test
@RackHD/corecommitters @nortonluo @iceiilin
> fix "Cannot assign to read only property '0' of string 'Task.Add.Hotspare'"

- lib/common/constants.js
- spec/lib/serializables/log-event-spec.js
When user install windows 2012, the logs include `productkey:      xxxxx-xxxxx-xxxxx-xxxxx`, which is private and should be redacted.
@RackHD/corecommitters @nortonluo @iceiilin
> redact productkey

- lib/models/lookup.js
- spec/lib/models/lookup-spec.js
A bug is reported about upper cases of MAC Address in lookups collection but cannot be queried. The reason is in on-core, we change the query to lower case before searching in mongoDB.
MAC Address can be either upper or lower case, but data in MongoDB is case sensitive, and insensitive operations could not leverage index and slow down the response. So modifying MAC address to lower case before updating documents, which is align with common practice in *nix such as dhcpd.
> [RAC-6786]Modify macAddress to lower case before writing to DB
